### ISSUE TITLE
Plugin cannot be installed

### ISSUE THREAD

**Issue by joethei** [nbossard/obsidian-CtrlXA#1]
Hi @nbossard

We have noticed that the latest release of your plugin cannot be installed currently.

This is due to the following reason:
- No release found for version 1.0.9

We will remove this plugin from the community plugins not fixed within 30 days.

- The Obsidian Team

**Comment by nbossard** [comment]
Hello @joethei , thanks for thhe information.

I was not aware that Obsidian was looking at my repo "main" branch to know if there are new versions. I thought it was listing the releases.
1.0.9 is the release in work progress, I am used to change number straight after releasing to not forget it. So i will change my git flow and prepare new version in a "develop" branch, this should fix the issue.

**Comment by nbossard** [comment]
@joethei. OK, reverted main branch to latest release  : 1.0.8

And reported the changes in progress to a new branch named "develop".

Tested in Obsidian, now obsidian no more suggests to update to 1.0.9

Closing the issue.
